language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
before_install:
- yes | sdkmanager "platforms;android-28"
before_script:
- "echo \"Build process is started \U0001F46F\""
- openssl aes-256-cbc -d -in $debugKeyStore.encrypted -k $DEBUG_ENCRYPT_SECRET_KEY >> $debugKeyStore
- openssl aes-256-cbc -d -in $releaseKeyStore.encrypted -k $RELEASE_ENCRYPT_SECRET_KEY >> $releaseKeyStore
- printf 'debugKeyAlias=%s\ndebugKeyPassword=%s\ndebugKeyStore=%s\ndebugStorePassword=%s\nreleaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s'
  $debugKeyAlias $debugKeyPassword $debugKeyStore $debugStorePassword $releaseKeyAlias
  $releaseKeyPassword $releaseKeyStore $releaseStorePassword > keystore.properties
script:
- "./gradlew androidDependencies"
- "./gradlew lint test"
- "./gradlew clean assembleRelease --no-daemon --stacktrace"
before_deploy:
- git config --local user.name "Faruk Cankaya"
- git config --local user.email "farukcankayaaa@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: buHDwR7nV3wGUGZETpOiAadRBZMx/CtO1pytwBGwYENJJy/0v2JrM5hnsa4RXjrsx0J/omVTECGlynUK3CeFekfA4GXEKgEB/cdzI2VL79qqRCTtJOJjLFAWchh15w5PlBHIR26w96agkYIitH0ESfU4rgSuWxj1VZQM3w8AEQ32uEvn+Qr6KvE/DH7RXT+AMGLpMGMULZ2TsfU1rqHJ67DV/fOCs30q9grHIthcGH3mjTATytfhBXrI1837rsoNOERhfsGaAKp15d3cX7KWr51gyMzJlMdzgJ5cjgiM4wcHwwtP/KC2I4+JnjsRh0qoqeYnQ8moL/XgoTwvPE7rN7MbvrsHwjT+ZRVFWxGhEqOx7J1FdQIzdhq0ZfEeTefzXNYPKZL5DjVBghhWWJjfrOK2CN9gOxqMxaFILR86mZ+xSlNvHDLYQwc3rlXK9Fszal5rRkPeWJSGJNCEDziCwwdpW06GERSUOLR37iDgcAp84dgp/s2jyhFpxpLTXAd9iG2bT5gfT7ll+dJizE8XeOFOIn0Fx7bGREfvgX+dYoRC0O89QTjWYXB+Syg8SNhGAUSFS24dW6Hn5IMMZVCYCDgl1sjaV34uT4wUGTl4MFJWysdc/C6BXYGAcd2By+TTpN/2oePygrBwaGiccbRPkn4Th4kduggOA0aowON0Xt4=
  file: 'app/build/outputs/apk/release/app-release.apk'
  overwrite: true
  skip_cleanup: true
  on:
    repo: farukcankaya/ciappsigningexample